### ISSUE TITLE
name option thorw an error

### ISSUE THREAD

**Issue by zoheirkhonyagar** [mycodeself/mongo-migrate-ts#15]
when I run `mongo-migrate new --name "my-name"` I've got an error
![Screenshot from 2020-04-16 12-43-44](https://user-images.githubusercontent.com/21988949/79431783-20ec9980-7fe0-11ea-8e25-e769efd84cca.png)

**Comment by mycodeself** [comment]
You must not use quotes. Can you try without It and tell me if it works?

Thanks

**Comment by zoheirkhonyagar** [comment]
yes, I tried but still I've got this error. it creates the migration file correctly. but just showed this error in the console. 
I have some suggestions for this cool tool I'm very interested to contribute.
it would be awesome if we could up & down a specific migration just by name.

**Comment by zoheirkhonyagar** [comment]
I checked and something was wrong with calling commander package

**Comment by mycodeself** [comment]
I've been doing some research and found that the problem is with the latest version of commander lib https://github.com/tj/commander.js/issues/1226

I've released a new version 1.0.9 that includes the fix and:

- Fix new command with --name parameter by disable store options as properties in commander lib.
- Add -n shortcut to new command.
- Upgrade dependencies.

Now everything works, test it and tell me if you have any other problem!
