### ISSUE TITLE
Unexpected Token export

### ISSUE THREAD

**Issue by ankur20us** [mycodeself/mongo-migrate-ts#33]
For all the commands, in windows we get **Unexpected Token export**

**Comment by mycodeself** [comment]
I think this was related to the usage of `process.env.PWD` this has been fixed in the latest release, see https://github.com/mycodeself/mongo-migrate-ts/pull/40/commits/bdfbf3fd45356c595ef0d187c84d665958c47c65

Unfortunately, I don't have windows to be able to test it, so feel free to reopen the issue if you're still having the same issue
